//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HDResource.rc
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDS_STRING3                     3
#define IDS_STRING4                     4
#define IDS_STRING5                     5
#define IDS_STRING6                     6
#define IDS_STRING7                     7
#define IDS_STRING8                     8
#define IDS_STRING9                     9
#define IDD_MAINDIALOG                  10
#define IDS_STRING10                    10
#define IDS_STRING11                    11
#define IDS_STRING12                    12
#define IDS_STRING13                    13
#define IDS_STRING14                    14
#define IDS_STRING15                    15
#define IDS_STRING16                    16
#define IDS_FUNCDTIONKEY1               17
#define IDS_FUNCDTIONKEY2               18
#define IDS_FUNCDTIONKEY3               19
#define IDS_FUNCDTIONKEY4               20
#define IDS_FUNCDTIONKEY5               21
#define IDS_FUNCDTIONKEY6               22
#define IDS_FUNCDTIONKEY7               23
#define IDS_FUNCDTIONKEY8               24
#define IDS_FUNCDTIONKEY9               25
#define IDS_FUNCDTIONKEY10              26
#define IDI_ICON1                       102
#define IDI_ICON2                       103
#define IDR_MENU1                       105
#define IDD_DIALOGABOUT                 106
#define IDD_DIALOGREADME                107
#define IDD_DIALOGHOTKEY                108
#define IDD_DIALOGOTHER                 110
#define IDC_CURSOR1                     111
#define IDB_BITMAP1                     112
#define IDD_DIALOG1                     117
#define IDD_DIALOGHISTORY               117
#define IDI_ICON3                       118
#define IDD_DIALOG_REGISTER             124
#define IDD_DIALOGPASSWORD              127
#define IDR_MENU2                       129
#define IDD_WIZARD_SELWINDOWANDICON     131
#define IDD_WIZARD_FINISH               132
#define IDB_HEADER                      134
#define IDD_WIZARD_BEGINBK              136
#define IDB_WATERMARK                   137
#define IDD_DIALOGBK                    138
#define IDI_ICON_NOICON                 139
#define IDI_ICON_UNKNOWN                140
#define IDI_ICON_DEFAULT                142
#define IDR_MENU3                       143
#define IDD_DIALOGQUICKHIDE             144
#define IDD_DIALOG_BACKTIP              145
#define IDB_TITLEBAR                    146
#define IDB_MINIMIZE                    147
#define IDB_MINIPRESS                   148
#define IDB_BOTTOM                      149
#define IDB_LEFTSIDE                    150
#define IDB_RIGHTSIDE                   151
#define IDB_LEFTEXT                     155
#define IDB_RIGHTEXT                    156
#define IDD_DIALOG_MOUSEMOTION          158
#define IDD_DIALOG_MULTILANGUAGE        159
#define IDD_DIALOG_AUTOUPDATE           161
#define IDR_MENU_JOBTIP                 162
#define IDD_DIALOG_BKWNDHOTKEY          163
#define IDD_DIALOG_CHANGEWNDTITLE       164
#define IDD_DIALOG_PROPERTY             165
#define IDD_PROPERTY_GENERAL            167
#define IDD_PROPERTY_ADDITIONAL         168
#define IDD_DIALOG_RESUMETIP            170
#define IDD_DIALOG_EXITTIP              171
#define IDI_ICON_INFORMATION            172
#define IDD_DIALOG2                     174
#define IDD_TAB_ALLWND                  179
#define IDD_TAB_TRAYICON                180
#define IDD_PANEL_ALLINFO               181
#define IDD_TAB_BKLIST                  182
#define IDR_MENU_TABTRAYLIST            183
#define IDR_MENU_BKTAB                  184
#define ID_DN_ICONA                     185
#define ID_DN_ICONI                     186
#define ID_UP_ICONA                     187
#define ID_UP_ICONI                     188
#define IDB_BACK                        190
#define IDB_HOVE                        191
#define IDB_PRESS                       192
#define IDB_DISABLE                     193
#define IDR_MENU_BKITEM                 195
#define IDD_TAB_WEBPAGE                 196
#define IDD_TAB_PROCESSLIST             197
#define IDR_MENU_PROCESSLIST            198
#define IDD_TAB_CLEANPRIV               199
#define IDD_DIALOG_CLEANPROGRESS        200
#define IDD_TAB_HIDEIP                  201
#define IDD_TAB_HIDEIPADVANCED          202
#define IDD_TAB_HIDEIP_ADVANCE          204
#define IDD_TAB_HIDEIP_GENERAL          205
#define IDD_TAB_AUTOHIDE                207
#define IDR_MENU_AUTOHIDE               208
#define IDB_TAB_ALLWND                  213
#define IDB_TAB_ADSUNION                214
#define IDB_TAB_TRAYICON                215
#define IDB_TAB_CLEAN                   216
#define IDB_TAB_HIDEIP                  217
#define IDB_TAB_AUTOHIDE                218
#define IDB_TAB_BKLIST                  219
#define IDI_ALLWND_HIDETHISWINDOW       220
#define IDI_ALLWND_REFRESH              221
#define IDI_INFO_OPTION                 222
#define IDI_INFO_HIDEICON               223
#define IDI_INFO_BKWIZARD               224
#define IDI_TRAY_HIDEICON               225
#define IDI_BK_SHOWITEM                 226
#define IDI_CLEAN_CLEANNOW              227
#define IDI_HIDEIP_HIDENOW              228
#define IDI_HIDEIP_RESTOREIP            229
#define IDI_HIDEIP_SEARCHIP             230
#define IDD_DIALOG_PASSWORD             231
#define IDC_LIST1                       1000
#define IDC_WINDOWSLIST                 1000
#define IDC_LIST_BK                     1000
#define IDC_BUTTON1                     1001
#define IDC_REFRESH                     1001
#define IDC_START                       1001
#define IDC_COMPLETEREG                 1001
#define IDC_BUTTON_SELPATH              1001
#define IDC_BUTTON2                     1002
#define IDC_RESERVE                     1002
#define IDC_DESKTOP                     1002
#define IDC_UPDATE                      1002
#define IDC_HOWREG                      1002
#define IDC_BUTTON_KEEPHIDE             1002
#define IDC_EXIT                        1003
#define IDC_QUICKLUNCH                  1003
#define IDC_BUTTON4                     1004
#define IDC_HIDEICON                    1004
#define IDC_BUTTON5                     1005
#define IDC_OPTION                      1005
#define IDC_BUTTON6                     1006
#define IDC_ABOUT                       1006
#define IDC_ADS                         1007
#define IDC_MOUSE                       1008
#define IDC_KEYBOARD                    1009
#define IDC_CALLWINDOW                  1010
#define IDC_RESTORE                     1011
#define IDC_EDIT1                       1012
#define IDC_EDITREADME                  1012
#define IDC_EDIT_PASSWORD               1012
#define IDC_EDIT_QQ                     1012
#define IDC_EDIT_PPATH                  1012
#define IDC_EDIT_WNDTITLE               1012
#define IDC_EDIT_PROCESSID              1012
#define IDC_SPIN                        1018
#define IDC_CHECKAUTORUN                1019
#define IDC_CHECK_DISABLESOUND          1019
#define IDC_CHECKMOUSE                  1020
#define IDC_RADIOKILL                   1022
#define IDC_RADIOSHOW                   1023
#define IDC_EDITINTERVAL                1024
#define IDC_CHECKREFRESH                1025
#define IDC_STATICEMAIL                 1026
#define IDC_STATICHTTP                  1027
#define IDC_EDITCREDIT                  1028
#define IDC_STAIICICON                  1032
#define IDC_STATICNAME                  1033
#define IDC_STATICCOPYRIGHT             1034
#define IDC_STATICRESERVED              1035
#define IDC_RICHEDIT21                  1036
#define IDC_RICHEDITHIST                1036
#define IDC_RICHEDIT2                   1037
#define IDC_RICHEDIT22                  1037
#define IDC_LISTVIEW                    1038
#define IDC_CHECK_AUTORUN               1040
#define IDC_CHECK_ADDQL                 1041
#define IDC_CHECK_ONTOP                 1042
#define IDC_STATIC_UPDATE               1047
#define IDC_EDIT_MIDDLECODE             1049
#define IDC_EDIT_RC1                    1050
#define IDC_EDIT_RC2                    1051
#define IDC_EDIT_RC3                    1052
#define IDC_EDIT_RC4                    1053
#define IDC_EDIT_RC5                    1054
#define IDC_SHOCKWAVEFLASH1             1056
#define IDC_CHECK_USEPASSWORD           1057
#define IDC_EDIT_VALIDATE               1058
#define IDC_CHECK_FUNCTIONKEY           1061
#define IDC_COMBO_FUNCTIONKEY           1062
#define IDC_LIST_ICONANDWINDOW          1063
#define IDC_STATIC_SOMETIP              1064
#define IDC_LIST_VALIDATE               1065
#define IDC_STATIC_BKGROUP              1066
#define IDC_STATIC_FOREGROUND           1067
#define IDC_STATIC_TIP1                 1068
#define IDC_CHECK_AUTOHIDE              1070
#define IDC_CHECK_HIDEMAINWND           1071
#define IDC_CHECK_HIDEICON              1072
#define IDC_CHECK_DOUBLECLICK           1073
#define IDC_CHECK_AUTOHIDEBK            1074
#define IDC_CHECK1                      1075
#define IDC_CHECK_SHOWBKTIP             1075
#define IDC_CHECK_HIDEPROCESS           1076
#define IDC_CHECK_AUTOMEM               1077
#define IDC_CHECK_HIDEPOPUP             1078
#define IDC_RADIO1                      1080
#define IDC_RADIO_RESERVE               1080
#define IDC_RADIO_AUTOUPDATE            1080
#define IDC_RADIO_BKITEMNOW             1080
#define IDC_RADIO2                      1081
#define IDC_RADIO_HIDE                  1081
#define IDC_RADIO_TIP                   1081
#define IDC_RADIO_BRINGITEM             1081
#define IDC_HOTKEYRES                   1082
#define IDC_HOTKEY_HIDEALL              1083
#define IDC_HOTKEY_SHOWSELF             1084
#define IDC_CHECKRESHK                  1085
#define IDC_HOTKEY_RES                  1087
#define IDC_HOTKEY_HA                   1088
#define IDC_HOTKEY_SS                   1089
#define IDC_CHECK_NEEDSTART             1093
#define IDC_CHECK_NOTSHOWICON           1095
#define IDC_CHECK_DONTSHOWTIP           1097
#define IDC_HOTKEY_TIPSS                1099
#define IDC_CHECK2                      1100
#define IDC_COMBO_PREDEFINE             1101
#define IDC_STATIC_MOUSE                1102
#define IDC_WIZARD                      1103
#define IDC_BKWIZARD                    1103
#define IDC_SHOWBK                      1104
#define IDC_STATIC_HIDEALLWINDOW        1105
#define IDC_STATIC_SHOWHIDEDRAGON       1106
#define IDC_STATIC_USEAGETIP            1107
#define IDC_STATIC_GMAILSTYLEADS        1108
#define IDC_STATIC_ISUSEMOUSE           1109
#define IDC_STATIC_HIDEALLWINDOWHOTKEY  1110
#define IDC_STATIC_SHOWHIDEDRAGONHOTKEY1 1111
#define IDC_CHECK_RIGHTFIRST            1112
#define IDC_STATIC_WHYUSEPASSWORD       1113
#define IDC_STATIC_PASSWORDUSETIP       1114
#define IDC_STATIC_PASSWORDLABEL        1115
#define IDC_STATIC_PASSWORDREENTER      1116
#define IDC_STATIC_BACKGROUNDOPTION     1117
#define IDC_STATIC_SYSTEMSETTING        1119
#define IDC_STATIC_SELECTED             1120
#define IDC_STATIC_OTEHRSYSTEM          1121
#define IDC_STATIC_WHENEXITWINDOW       1122
#define IDC_STATIC_REFRESHOPTION        1123
#define IDC_STATIC_IMNUMBER             1124
#define IDC_STATIC_BKTIP_THROUGHHOTKEY  1125
#define IDC_STATIC_BK_OR                1126
#define IDC_STATIC_BK_RUNAGAIN          1127
#define IDC_STATIC_RESHOW               1128
#define IDC_CLOSE                       1129
#define IDC_STATIC_WELCOMETOUSEWIZARD   1130
#define IDC_STATIC_THISWIZARDTOHELPYOU  1131
#define IDC_STATIC_SPECIFYICONTOBK      1132
#define IDC_STATIC_SPECIFYPROGRAMTOBK   1133
#define IDC_STATIC_CLICKFINISHTOHIDEWINDOW 1134
#define IDC_STATIC_AUTOUPDATESEL        1138
#define IDC_STATIC_PROMPTSTATIC         1139
#define IDC_STATIC_SHOWHIDEDRAGONHOTKEY 1140
#define IDC_HOTKEY_BKWINDOW             1141
#define IDC_OK                          1142
#define IDC_CANCEL                      1143
#define IDC_STATIC_ACQUIREHOTKEY        1144
#define IDC_STATIC_HOTKEYLABEL          1145
#define ID_OK                           1146
#define ID_CANCEL                       1147
#define IDC_STATIC_DONOTEMPTY           1148
#define IDC_EDIT_PROCESSNAME            1149
#define IDC_EDIT_WNDNUM                 1150
#define IDC_EDIT_ORGTITLE               1151
#define IDC_EDIT_NEWTITLE               1152
#define IDC_EDIT_TRANSPARENT            1153
#define IDC_HOTKEY_BK                   1154
#define IDC_EDIT_AUTORESERVE            1155
#define IDC_LIST_TITLEANDHANDLE         1156
#define IDC_ICON_ORG                    1157
#define IDC_ICON_NEW                    1158
#define IDC_ICON_TRAY                   1159
#define IDC_EDIT_PAGE_PROCESSID         1160
#define IDC_EDIT_PAGE_PROCESSNAME       1161
#define IDC_EDIT_PAGE_WNDNUM            1162
#define IDC_LIST_PAGE_TITLEANDHANDLE    1163
#define IDC_EDIT_PAGE_ORGTITLE          1164
#define IDC_EDIT_PAGE_NEWTITLE          1165
#define IDC_EDIT_PAGE_TRANSPARENT       1166
#define IDC_EDIT_PAGE_AUTORESERVE       1167
#define IDC_HOTKEY_PAGE_BK              1168
#define IDC_ICON_PAGE_ORG               1169
#define IDC_ICON_PAGE_NEW               1170
#define IDC_ICON_PAGE_TRAY              1171
#define IDC_BUTTON_SHOWALL              1172
#define IDC_LIST_HIDEDWND               1173
#define IDC_STATIC_PROCESSID            1174
#define IDC_STATIC_PROCESSNAME          1175
#define IDC_STATIC_VISIBLEWNDNUM        1176
#define IDC_STATIC_WNDTITLEANDHANDLE    1177
#define IDC_STATIC_ORGTITLE             1178
#define IDC_STATIC_NEWTITLE             1179
#define IDC_STATIC_ORGICON              1180
#define IDC_STATIC_NEWICON              1181
#define IDC_STATIC_TRAYICON             1182
#define IDC_STATIC_PROPERTY_BKHOTKEY    1183
#define IDC_STATIC_TRANSPARENT          1184
#define IDC_STATIC_AUTORESERVE          1185
#define IDC_STATIC_INPUTWNDTITLE        1186
#define IDC_STATIC_ORGWNDTITLE          1188
#define IDC_STATIC_NOTRAYICON           1190
#define IDC_STATIC_WELCOMREGISTER       1191
#define IDC_STATIC_BENIFIT1             1193
#define IDC_STATIC_BENEFIT2             1194
#define IDC_STATIC_FEEDBACK             1194
#define IDC_STATIC_BENIFIT3             1195
#define IDC_STATIC_ABOUTDETAIL          1197
#define IDC_STATIC_ORGCODE              1199
#define IDC_STATIC_REGCODE              1200
#define IDC_CANCELREG                   1201
#define IDC_STATIC_AFTERREGISTER        1202
#define IDC_COMBO_WNDTITLE              1203
#define IDC_STATIC_BKNOTEMPTY           1204
#define IDC_STATIC_TIPTEXT              1205
#define IDC_STATIC_TIPTEXT2             1206
#define IDC_STATIC_TIPICON              1207
#define IDC_CHECK_DONTSHOWEXITTIP       1208
#define IDC_CHECK_MIDDBUTTON            1212
#define IDC_STATIC_PTY_ICON             1213
#define IDC_STATIC_LIMIT                1217
#define IDC_STATIC_SUPPORTMAIL          1218
#define IDC_STATIC_BUYLINK              1219
#define IDC_STATIC_PLEASEEMAIL          1220
#define IDC_CHECK_SAVEHK                1221
#define IDC_TAB_LIST_ALLWND             1223
#define IDC_TAB_BTN_REFRESHLIST         1224
#define IDC_STATIC_INFO_MOUSE           1225
#define IDC_INFO_MOUSE                  1226
#define IDC_CHECK_INFO_ONTOP            1227
#define IDC_INFO_OPTION                 1228
#define IDC_INFO_HIDEICON               1229
#define IDC_STATIC_INFO_HIDEALLWINDOW   1230
#define IDC_STATIC_INFO_SHOWHIDEDRAGON  1231
#define IDC_HOTKEY_INFO_HA              1232
#define IDC_HOTKEY_INFO_SS              1233
#define IDC_INFO_BKWIZARD               1234
#define IDC_INFO_UPDATE                 1235
#define IDC_STATIC_INFO_UPDATE          1236
#define IDC_STATIC_INFO_ICON            1237
#define IDC_STATIC_INFO_GROUP           1238
#define IDC_TAB_BTN_REFRESH             1239
#define IDC_TAB_BKLIST                  1240
#define IDC_TAB_CHECK_AUTOHIDE          1241
#define IDC_TAB_SHOWBK                  1242
#define IDC_TAB_TRAYLIST                1243
#define IDC_TAB_CHECK_SELHIDE           1244
#define IDC_CHECK_HIDEALLTRAY           1245
#define IDC_CHECK_CLOSEINFOPANEL        1247
#define IDC_SAVECHANGE                  1248
#define IDC_STATIC_EXPANDINFO           1249
#define IDC_CHECK_NOTSHOWPROCESS        1250
#define IDC_STATIC_WEBPOS               1252
#define IDC_TAB_PROCESSLIST             1253
#define IDC_PROCESSLIST_REFRESH         1254
#define IDC_CLEAN_TREE                  1255
#define IDC_CLEAN_CLEANNOW              1256
#define IDC_CLEAN_SELALL                1257
#define IDC_CLEAN_UNSELALL              1258
#define IDC_CLEAN_CLEANAFTER            1259
#define IDC_PROGRESS_PROGRESS           1260
#define IDC_PROGRESS_INFO               1261
#define IDC_PROGRESS_CANCEL             1262
#define IDC_HIDEIP_HIDEIP               1263
#define IDC_CLEANPRIV_TIP               1264
#define IDC_CHECK_CLEANAFTERHIDE        1267
#define IDC_HIDEIP_USETHISPROXY         1271
#define IDC_HIDEIP_ADV_RESTOREIP        1272
#define IDC_HIDEIP_HIDENOW              1273
#define IDC_HIDEIP_ADVANCED             1274
#define IDC_DOWORK_PROGRESS             1275
#define IDC_USE_INFO                    1276
#define IDC_HIDEIP_ADV_IPSTATE          1277
#define IDC_HIDEIP_IPLIST               1278
#define IDC_HIDEIP_SELSERVER            1280
#define IDC_HIDEIP_STATICHIDEIP         1282
#define IDC_HIDEIP_STOPSEARCH           1283
#define IDC_HIDEIP_IPSTATE              1284
#define IDC_HIDEIP_RESTOREIP            1285
#define IDC_HIDEIP_SEARCHNOW            1286
#define IDC_HIDEIP_YOURIP               1287
#define IDC_HIDEIP_ADV_STOPSEARCH       1288
#define IDC_TRAYPAGE_HIDETRAY           1289
#define IDC_TABPAGE_ADLINK              1290
#define IDC_HIDEIP_ADLINK               1291
#define IDC_PROCESSPAGE_HIDE            1292
#define IDC_PROCESSPAGE_ADLINK          1293
#define IDC_BK_ADLINK                   1294
#define IDC_HIDEIP_ADV_ADLINK           1295
#define IDC_HIDEIP_ADV_SEARCHFAIL       1296
#define IDC_HIDEIP_SEARCHFAIL           1297
#define IDC_STATIC_BENIFIT2             1298
#define IDC_AUTOHIDE_LIST               1300
#define IDC_AUTOHIDE_ADD                1301
#define IDC_AUTOHIDE_ADLINK             1302
#define IDC_AUTOHIDE_TIP                1303
#define IDC_WNDLIST_HIDE                1304
#define IDC_WNDLIST_ADS                 1305
#define IDC_STATIC_AUTOHIDE             1306
#define IDC_CHECK_AUTOHIDEANY           1307
#define IDC_AUTOHIDE_DEL                1308
#define IDC_AUTOHIDE_ENABLEAH           1309
#define IDC_CLEANPRIV_ADS               1310
#define IDC_STATIC_DOUBLECLICK          1311
#define IDC_RADIO_CHECKITEM             1312
#define IDC_CHECK_HIDEAUTOHIDE          1313
#define IDC_PASSWORD_TIP                1314
#define IDC_PASSWORDDLG_PASSWORD        1315
#define IDC_PASSWORD_EDIT               1316
#define IDC_PASSWORDDLG_OK              1317
#define IDC_PASSWORDDLG_CANCEL          1318
#define IDC_PASSWORDDLG_WRONGPASSWORD   1319
#define IDC_ABOUT_STATIC_LICENSETO      1320
#define IDC_ABOUT_STATIC_LICENSENAME    1321
#define IDC_STATIC_ADS1                 1322
#define IDC_TRAY_ADS                    1323
#define IDC_BK_ADS                      1324
#define IDC_WEB_ADS                     1325
#define IDC_CLEAN_ADS                   1326
#define IDC_AUTOHIDE_ADS                1327
#define IDC_HIDEIPGEN_ADS               1328
#define IDC_HIDEIPADV_ADS               1329
#define IDC_CHECK_HIDEEXITPROCESS       1330
#define IDC_HIDEIP_GENERAL              1505
#define IDC_HIDEIP_BTN_GENERAL          1505
#define IDC_BUTTON3                     1663
#define IDC_SHOWICON                    1664
#define IDC_CLEAN_BK                    1665
#define IDM_SHOWWINDOW                  40001
#define IDM_ABOUT                       40002
#define IDM_OPTION                      40003
#define IDM_HIDEICON                    40004
#define IDM_EXIT                        40005
#define IDM_UPDATE                      40006
#define IDM_SUGGEST                     40007
#define IDM_REGISTER                    40008
#define IDM_USERMANUAL                  40009
#define IDM_ONTOP                       40010
#define IDM_TRAYONTOP                   40011
#define IDM_TOBACK                      40018
#define IDM_AUTORESERVE                 40019
#define IDM_SPECBK                      40021
#define IDM_HIDEPROCESS                 40022
#define IDM_HIDETIP                     40024
#define IDM_CANCELRESERVE               40025
#define IDM_BLOG                        40026
#define IDM_XPQH                        40027
#define IDM_XPBK                        40028
#define IDM_CHINESE                     40029
#define IDM_ENGLISH                     40030
#define IDM_JAPANESE                    40031
#define IDM_ACQUIRELANGUAGE             40032
#define IDM_TRANSPARENT_MOSTHIGH        40033
#define IDM_TRANSPARENT_RESTORE         40035
#define IDM_TRANSPARENT_MIDDLE          40036
#define IDM_TRANSPARENT_LOW             40037
#define IDM_TRANSPARENT_MIDDLEHIGH      40040
#define IDM_TRANSPARENT_MIDDLELOW       40041
#define IDM_JOB_TIP1                    40042
#define IDM_JOB_TIP2                    40043
#define IDM_JOB_TIP3                    40044
#define IDM_RESERVE                     40045
#define IDM_CHANGEICON                  40046
#define IDM_CHANGETITLE                 40047
#define IDM_BKWNDHOTKEY                 40048
#define IDM_TOBK                        40049
#define IDM_PROPERTY                    40050
#define IDM_RESTOREICONTITLE            40051
#define IDM_UNREGISTERHK                40052
#define IDM_BUYONLINE                   40053
#define IDM_TESTTLEICON                 40054
#define IDM_RESERVESEL                  40055
#define IDM_HIDESEL                     40056
#define IDM_XPDISGUISE                  40057
#define IDM_TAB_TRAY_LIST               40058
#define IDM_BKTAB_BKWIZARD              40059
#define IDM_REMEMBER                    40060
#define IDM_EXPANDINFOPANEL             40062
#define IDM_BKITEM_SHOW                 40063
#define IDM_NEWCOMMERMODEL              40064
#define IDM_VIDEOTURORIAL               40065
#define IDM_HIDEHDPROCESS               40066
#define IDM_PROCESSLIST_HIDE            40067
#define IDM_PROCESSLIST_END             40068
#define IDM_HELP_CLEAN                  40069
#define IDM_HELP_HIDEIP                 40070
#define IDM_ADDAUTOHIDE                 40071
#define IDM_TAB_TRAY_ADDAUTOHIDE        40072
#define IDM_SETTOTOP                    40073
#define IDM_AUTOHIDE_ADD                40074
#define IDM_AUTOHIDE_DEL                40075

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         40077
#define _APS_NEXT_CONTROL_VALUE         1331
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
